import React, { useState } from 'react';
import { SongData } from '../types';

interface SongSheetProps {
  data: SongData;
}

const SongSheet: React.FC<SongSheetProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const textContent = data.sections.map(section => {
      return `[${section.sectionName}]\n` + section.lines.map(line => `${line.tabs}\n${line.lyric}`).join('\n\n');
    }).join('\n\n');
    
    const fullText = `${data.title} - ${data.artist}\n(Generated by HarmoTab AI)\n\n${textContent}`;
    
    navigator.clipboard.writeText(fullText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="w-full max-w-4xl mx-auto animate-fade-in pb-20">
      {/* Header Card */}
      <div className="bg-slate-800/90 backdrop-blur-xl border border-slate-700 rounded-3xl p-6 md:p-10 mb-10 shadow-2xl relative overflow-hidden group">
        {/* Decorative Background */}
        <div className="absolute -top-20 -right-20 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl group-hover:bg-indigo-500/20 transition-colors duration-700"></div>
        <div className="absolute -bottom-20 -left-20 w-72 h-72 bg-purple-500/10 rounded-full blur-3xl group-hover:bg-purple-500/20 transition-colors duration-700"></div>
        
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start gap-6">
            <div className="flex-1 space-y-2">
              <h1 className="text-4xl md:text-6xl font-extrabold text-white tracking-tight leading-tight drop-shadow-sm">
                {data.title}
              </h1>
              <div className="flex items-center gap-3 text-xl text-indigo-300 font-medium">
                <span className="w-8 h-0.5 bg-indigo-500/50 rounded-full"></span>
                {data.artist}
              </div>
            </div>

            <button 
              onClick={handleCopy}
              className="flex items-center gap-2 px-5 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-sm font-semibold transition-all hover:scale-105 text-slate-200 active:scale-95"
              aria-label="Copy tablature to clipboard"
            >
              {copied ? (
                <>
                  <svg className="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                  Copy Tabs
                </>
              )}
            </button>
        </div>
        
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-10">
            <div className="bg-slate-950/40 p-4 rounded-2xl border border-white/5 backdrop-blur-sm">
                <span className="block text-slate-400 text-xs uppercase tracking-wider font-bold mb-1">Key</span>
                <span className="font-mono text-lg text-white font-semibold">{data.key}</span>
            </div>
            <div className="bg-slate-950/40 p-4 rounded-2xl border border-white/5 backdrop-blur-sm">
                <span className="block text-slate-400 text-xs uppercase tracking-wider font-bold mb-1">Difficulty</span>
                <div className="flex items-center gap-2">
                  <span className={`w-2.5 h-2.5 rounded-full animate-pulse ${
                      data.difficulty.toLowerCase().includes('begin') ? 'bg-emerald-400' : 
                      data.difficulty.toLowerCase().includes('inter') ? 'bg-amber-400' : 'bg-rose-500'
                  }`}></span>
                  <span className="font-mono text-lg text-white font-semibold">{data.difficulty}</span>
                </div>
            </div>
            <div className="bg-slate-950/40 p-4 rounded-2xl border border-white/5 backdrop-blur-sm">
                <span className="block text-slate-400 text-xs uppercase tracking-wider font-bold mb-1">Harmonica</span>
                <span className="font-mono text-lg text-white font-semibold">{data.recommendedHarmonica}</span>
            </div>
        </div>
      </div>

      {/* Tabs Sheet */}
      <div className="space-y-8">
        {data.sections.map((section, sIndex) => (
          <div key={sIndex} className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 md:p-8 shadow-xl relative overflow-hidden">
             {/* Section Number Background */}
            <div className="absolute -right-4 -top-4 text-9xl font-bold text-white/5 pointer-events-none select-none font-mono">
              {sIndex + 1}
            </div>

            <h3 className="relative z-10 text-sm font-bold text-indigo-400 uppercase tracking-widest mb-8 border-b border-indigo-500/20 pb-3 inline-block">
              {section.sectionName}
            </h3>
            
            <div className="space-y-10 relative z-10">
              {section.lines.map((line, lIndex) => (
                <div key={lIndex} className="group">
                  {/* Tabs Line (Scrollable Container) */}
                  <div className="relative">
                    <div className="font-mono text-2xl md:text-3xl tracking-wider text-cyan-300 mb-2 overflow-x-auto whitespace-nowrap scrollbar-hide pb-2 pl-1">
                      {line.tabs}
                    </div>
                    {/* Fade indicators for scrolling */}
                    <div className="absolute inset-y-0 right-0 w-8 bg-gradient-to-l from-slate-900/80 to-transparent pointer-events-none md:hidden"></div>
                  </div>
                  
                  {/* Lyrics Line */}
                  <div className="text-slate-300 text-lg md:text-xl font-serif leading-relaxed pl-1 border-l-2 border-transparent group-hover:border-indigo-500/50 group-hover:pl-4 transition-all duration-300">
                    {line.lyric || <span className="italic text-slate-600 text-base">(Instrumental)</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Sources Footer */}
      {data.sources && data.sources.length > 0 && (
        <div className="mt-12 border-t border-slate-800/60 pt-8">
          <h4 className="flex items-center gap-2 text-slate-500 uppercase tracking-wider font-bold text-xs mb-4">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /></svg>
            Verified Sources
          </h4>
          <div className="flex flex-wrap gap-3">
            {data.sources.map((source, idx) => (
               <a 
                 key={idx} 
                 href={source.uri} 
                 target="_blank" 
                 rel="noopener noreferrer"
                 className="group flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 hover:border-indigo-500/50 hover:bg-slate-800 text-slate-400 hover:text-indigo-300 transition-all duration-200 max-w-full sm:max-w-sm"
               >
                 <span className="truncate text-sm font-medium">{source.title}</span>
                 <svg className="w-3 h-3 flex-shrink-0 opacity-50 group-hover:opacity-100 transition-opacity" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
               </a>
            ))}
          </div>
        </div>
      )}
      
      {/* Legend */}
      <div className="mt-16 flex justify-center">
        <div className="inline-flex items-center gap-8 bg-slate-900 px-8 py-4 rounded-full border border-slate-800 shadow-lg">
           <div className="flex flex-col items-center gap-1">
             <span className="flex items-center justify-center w-8 h-8 bg-cyan-500/10 text-cyan-400 rounded-full text-sm font-bold">+4</span>
             <span className="text-slate-500 text-xs font-bold uppercase tracking-wide">Blow</span>
           </div>
           <div className="w-px h-8 bg-slate-800"></div>
           <div className="flex flex-col items-center gap-1">
             <span className="flex items-center justify-center w-8 h-8 bg-white/5 text-slate-300 rounded-full text-sm font-bold">-4</span>
             <span className="text-slate-500 text-xs font-bold uppercase tracking-wide">Draw</span>
           </div>
           <div className="w-px h-8 bg-slate-800"></div>
           <div className="flex flex-col items-center gap-1">
             <span className="flex items-center justify-center w-8 h-8 bg-white/5 text-slate-300 rounded-full text-sm font-bold">-4'</span>
             <span className="text-slate-500 text-xs font-bold uppercase tracking-wide">Bend</span>
           </div>
        </div>
      </div>
    </div>
  );
};

export default SongSheet;